sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src,e2e
sonar.test.inclusions=src/**/*.unit.test.ts,src/**/*.unit.test.tsx,src/**/*.integration.test.ts,src/**/*.integration.test.tsx,e2e/**/*.spec.ts
sonar.exclusions=src/**/*.unit.test.ts,src/**/*.unit.test.tsx,src/**/*.integration.test.ts,src/**/*.integration.test.tsx,src/test/**,src-js/**,dist/**,coverage/**,playwright-report/**,test-results/**
